Sprint_2
sergkolosov/qa_python pull request #2
Opened 2023-05-14 20:53 UTC by sergkolosov

2023-05-15 19:25 UTC, kadirovgm requested changes

2023-05-16 19:23 UTC, sergkolosov commented on tests.py
> +        assert self.collector.get_books_rating() == {self.book_1: 1, self.book_2: 1, self.book_3: 1}
Согласен. Исправил.

2023-05-16 19:44 UTC, sergkolosov commented on tests.py
> +        assert self.collector.get_books_rating()[self.book_1] == 10
Не понял коммента. В 51 строке используется именно get_book_rating

2023-05-16 20:08 UTC, kadirovgm commented on tests.py
> +        assert self.collector.get_books_rating()[self.book_1] == 10
Нет, у ты используешь `get_books_rating` для вывода словаря и обращаешься в элементу словаря, а у нас есть специальный метод `get_book_rating`, где как раз по названию книги выводится его рейтинг

2023-05-16 20:14 UTC, sergkolosov commented on tests.py
> +        assert self.collector.get_books_rating()[self.book_1] == 10
Возможно речи о методе get(), для получения значения по ключу? Исправил.

2023-05-16 21:22 UTC, sergkolosov commented on tests.py
> +        assert self.collector.get_books_rating()[self.book_1] == 10
Всё, разобрался. Спасибо!

2023-05-17 15:11 UTC, kadirovgm approved these changes

2023-05-17 15:11 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('boundary_values', [1, 2, 9, 10])
Можно лучше: граничные значения скорее: 0 ->1, 1->1, 10->10, 11->1
Можно было два теста сделать для валидных и невалидных значений

2023-05-31 17:31 UTC, merged